Ref/file separation (#12)
* started writing defintion for pipe.h and pipe.c

* changed numPipes to NUM_PIPES

* complted pipe functionality, just need to test now

* Started moving files around.

* added new files for bird. now need to fix main.c

* Added switch on enum to handle application loop in main.c and game.c file to handle game loop

* Changed Tick, Draw and Init to not be overloaded.

* Removed raylib.h from game.c and updated main.c to transition between states.

* Changed makefile to involve additional src files and include directory.

* Resolved most compilation errors as a result of not using a linter. Still need to resolve undefined reference to Pipe.h functions.

* Fixed unmatching function signatures between pipe.h and pipe.c

* Game is now compiling and added changes to change ApplicationState to QUITTING when ESC is pressed. Bird is drawing repeatedly and Pipes aren't drawing.

* Added ClearBackground in main.c to clear frame buffer.

---------

Co-authored-by: Ramon <ramontovar17@gmail.com>